
baseurl: https://morrislabpc.org/
=======

title: Morris Lab
theme: hugo-creative-portfolio-theme
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
languageCode: en-us
disqusShortname: ''
googleAnalytics: ''
params:
  copyright: '&copy;2021 Dr. Joanna Morris Department of Psychology, Providence College'
  description: Describe your website
  email: you@yoursite.com
  navlinks:
    - home: yes
      name: Home
      url: portfolio/
    - name: About
      url: about/
    - name: Get in touch
      url: contact/
  sidebarAbout:

    
=======
    - This is the website for the Human Psychophysiology Lab at Providence College, led by Dr. Joanna Morris.  We study human cognition, particularly language, using event related potentials. To learn more about our research please contact us. We would love to hear from you.

  social:
    email: email@example.com
    facebook: https://www.facebook.com/morris.joanna
    github: https://github.com/joannamorris
#    gitlab: full profile url in gitlab
    googleplus: https://scholar.google.com/citations?user=Qw8c8lQAAAAJ&hl=en
#    instagram: full profile url in instagram
    linkedin: full profile url in linkedin
#    stackoverflow: full profile url in stackoverflow
#    twitter: full profile url in twitter
#    whatsapp: wa.me service link
#    youtube: full profile url in youtube
  style: default
