
baseurl: /

title: Morris Lab
theme: hugo-creative-portfolio-theme
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
languageCode: en-us
disqusShortname: ''
googleAnalytics: 'G-VT7DER09PC'
params:
  copyright: PCHPL Logo &copy; 2021 Alec Nicholson
  style: default
  description: This is the website for the Human Psychophysiology Lab at PC.
  email: https://formspree.io/f/xyylqddv
  navlinks:
    - home: yes
      name: Lab Home
      url: about/
    - name: Research Projects
      url: projects/
    - name: General Lab Information
      url: info/
    - name: Our Current Students
      url: team/
    - name: Our Graduates
      url: graduates/
    - name: Tutorials
      url: tutorials/
    - name: Get in touch
      url: contact/
    - name: M21 Qualtrics Survey
      url: https://providence.az1.qualtrics.com/jfe/form/SV_5BYBWCrPez7ADA2

  sidebarAbout:
    - This is the website for the Human Psychophysiology Lab at Providence College.

  social:
    email: jmorris6@providence.edu
    facebook: https://www.facebook.com/morris.joanna
    github: https://github.com/joannamorris
#   gitlab: full profile url in gitlab
    googleplus: https://scholar.google.com/citations?user=Qw8c8lQAAAAJ&hl=en
#   instagram: full profile url in instagram
    linkedin: https://www.linkedin.com/in/joanna-morris-3278278/
#   stackoverflow: full profile url in stackoverflow
#   twitter: full profile url in twitter
#   whatsapp: wa.me service link
#   youtube: full profile url in youtube
