baseurl: /
title: Morris Lab
theme: hugo-creative-portfolio-theme
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
languageCode: en-us
disqusShortname: ''
googleAnalytics: 'G-G1VNKNRF5D'

# Hugo Configure Markup
# More info: https://gohugo.io/getting-started/configuration-markup#
markup:
  goldmark:
    extensions:
      passthrough:
        delimiters:
          block:
          - - \[
            - \]
          - - $$
            - $$
          inline:
          - - \(
            - \)
        enable: true

# Social links in footer, support github,twitter,stackoverflow,facebook




# Site parameters
params:
  math: true
  copyright: PCHPL Logo &copy; 2021 Alec Nicholson
  style: default
  description: This is the website for the Human Psychophysiology Lab at PC.
  formspree_id: xyylqddv

  navlinks:
    - home: yes
      name: Lab Home
      url: info/
    - name: About
      url: about/
    - name: Research Projects
      url: projects/
    - name: Tutorials
      url: tutorials/
    - name: Our Current Students
      url: team/
    - name: Our Graduates
      url: graduates/
    - name: Get in touch
      url: contact/
   
  social:
    email: 'jmorris6@providence.edu'
    github: 'https://github.com/joannamorris'
    googleplus: 'https://scholar.google.com/citations?user=Qw8c8lQAAAAJ&hl=en'
    linkedin: 'https://www.linkedin.com/in/joanna-morris-3278278/'
  
  sidebarAbout:
    - This is the website for the Human Psychophysiology Lab at Providence College.



